version: '3'

volumes:
  postgres_data:
      driver: local
services:
  postgres:
      image: postgres:15-alpine
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      networks:
        - default
  keycloak:
      image: "keycloak/keycloak"
      container_name: keycloak
      command:
        - "start-dev"
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
        KC_HEALTH_ENABLED: true
        KC_METRICS_ENABLED: true
        KC_FEATURES: scripts
      ports:
        - "8080:8080"
      depends_on:
        - postgres
      networks:
        - default
  backend:
    build:
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    restart:
      on-failure
    networks:
        - default
